In [33]:
import os
import  imageio
import pandas as pd

basedir =   "dog-and-cats-images/train/"
catimages = os.listdir(basedir + "cats")
dogimages = os.listdir(basedir + "dogs")

In [34]:
print(catimages)

['cat_103.jpg', 'cat_445.jpg', 'cat_164.jpg', 'cat_224.jpg', 'cat_59.jpg', 'cat_276.jpg', 'cat_497.jpg', 'cat_363.jpg', 'cat_153.jpg', 'cat_336.jpg', 'cat_589.jpg', 'cat_34.jpg', 'cat_120.jpg', 'cat_505.jpg', 'cat_132.jpg', 'cat_362.jpg', 'cat_423.jpg', 'cat_10.jpg', 'cat_532.jpg', 'cat_200.jpg', 'cat_257.jpg', 'cat_172.jpg', 'cat_263.jpg', 'cat_12.jpg', 'cat_177.jpg', 'cat_75.jpg', 'cat_201.jpg', 'cat_487.jpg', 'cat_133.jpg', 'cat_506.jpg', 'cat_393.jpg', 'cat_195.jpg', 'cat_39.jpg', 'cat_24.jpg', 'cat_214.jpg', 'cat_134.jpg', 'cat_260.jpg', 'cat_388.jpg', 'cat_209.jpg', 'cat_165.jpg', 'cat_84.jpg', 'cat_604.jpg', 'cat_536.jpg', 'cat_311.jpg', 'cat_246.jpg', 'cat_434.jpg', 'cat_183.jpg', 'cat_15.jpg', 'cat_376.jpg', 'cat_531.jpg', 'cat_548.jpg', 'cat_567.jpg', 'cat_194.jpg', 'cat_400.jpg', 'cat_463.jpg', 'cat_13.jpg', 'cat_438.jpg', 'cat_64.jpg', 'cat_397.jpg', 'cat_429.jpg', 'cat_219.jpg', 'cat_3.jpg', 'cat_483.jpg', 'cat_396.jpg', 'cat_95.jpg', 'cat_270.jpg', 'cat_535.jpg', 'cat_402

In [35]:
print(dogimages)

['dog_479.jpg', 'dog_287.jpg', 'dog_231.jpg', 'dog_509.jpg', 'dog_277.jpg', 'dog_33.jpg', 'dog_320.jpg', 'dog_32.jpg', 'dog_401.jpg', 'dog_342.jpg', 'dog_451.jpg', 'dog_324.jpg', 'dog_448.jpg', 'dog_381.jpg', 'dog_392.jpg', 'dog_195.jpg', 'dog_474.jpg', 'dog_505.jpg', 'dog_338.jpg', 'dog_251.jpg', 'dog_270.jpg', 'dog_77.jpg', 'dog_393.jpg', 'dog_294.jpg', 'dog_256.jpg', 'dog_162.jpg', 'dog_106.jpg', 'dog_532.jpg', 'dog_378.jpg', 'dog_576.jpg', 'dog_291.jpg', 'dog_139.jpg', 'dog_192.jpg', 'dog_97.jpg', 'dog_475.jpg', 'dog_513.jpg', 'dog_203.jpg', 'dog_221.jpg', 'dog_193.jpg', 'dog_11.jpg', 'dog_128.jpg', 'dog_290.jpg', 'dog_446.jpg', 'dog_391.jpg', 'dog_151.jpg', 'dog_226.jpg', 'dog_560.jpg', 'dog_212.jpg', 'dog_51.jpg', 'dog_152.jpg', 'dog_56.jpg', 'dog_444.jpg', 'dog_268.jpg', 'dog_204.jpg', 'dog_332.jpg', 'dog_412.jpg', 'dog_407.jpg', 'dog_432.jpg', 'dog_69.jpg', 'dog_259.jpg', 'dog_468.jpg', 'dog_47.jpg', 'dog_206.jpg', 'dog_458.jpg', 'dog_45.jpg', 'dog_29.jpg', 'dog_136.jpg', 'dog_

In [36]:
catVec = []
dogVec = []
catdir = basedir + "cats"
dogdir = basedir + "dogs"

In [37]:
cnt = 1   ## Testing Code
for img in catimages:
    ## img = imageio.imread(f"cat_/{img}")
    current_file = catdir + "/" + img
    print("Processing file : " + current_file )
    img = imageio.imread(f"{catdir}/{img}")
    ar = img.flatten()
    catVec.append(ar) 
    cnt = cnt + 1
    if cnt > 5:  ## Testing Code
        break    ## Testing Code


catdf = pd.DataFrame(catVec)    
catdf.insert(loc=0,column ="label",value=1)

Processing file : dog-and-cats-images/train/cats/cat_103.jpg
Processing file : dog-and-cats-images/train/cats/cat_445.jpg
Processing file : dog-and-cats-images/train/cats/cat_164.jpg
Processing file : dog-and-cats-images/train/cats/cat_224.jpg
Processing file : dog-and-cats-images/train/cats/cat_59.jpg


/tmp/ipykernel_11869/1354220807.py:6: DeprecationWarning: Starting with ImageIO v3 the behavior of this function will switch to that of iio.v3.imread. To keep the current behavior (and make this warning disappear) use `import imageio.v2 as imageio` or call `imageio.v2.imread` directly.
  img = imageio.imread(f"{catdir}/{img}")


In [38]:
print(catdf.head(5))

   label    0    1    2    3    4    5    6    7    8  ...  2457590  2457591   
0      1   93   87   65   89   83   61   81   75   53  ...      NaN      NaN  \
1      1  222  216  218  222  216  218  222  216  218  ...      NaN      NaN   
2      1   36   67   36   36   67   36   36   67   36  ...      NaN      NaN   
3      1    0    0    0    0    0    0    0    0    0  ...      NaN      NaN   
4      1  152  171  143  152  171  143  152  171  143  ...     39.0    203.0   

   2457592  2457593  2457594  2457595  2457596  2457597  2457598  2457599  
0      NaN      NaN      NaN      NaN      NaN      NaN      NaN      NaN  
1      NaN      NaN      NaN      NaN      NaN      NaN      NaN      NaN  
2      NaN      NaN      NaN      NaN      NaN      NaN      NaN      NaN  
3      NaN      NaN      NaN      NaN      NaN      NaN      NaN      NaN  
4    201.0     39.0    203.0    201.0     39.0    203.0    201.0     39.0  

[5 rows x 2457601 columns]


In [39]:
cnt = 1   ## Testing Code
for img in dogimages:
       current_file = dogdir + "/" + img
       print("Processing file : " + current_file )
       img = imageio.imread(f"{dogdir}/{img}")
       ar = img.flatten()
       dogVec.append(ar)   
       cnt = cnt + 1
       if cnt > 5:  ## Testing Code
           break    ## Testing Code
       
dogdf = pd.DataFrame(dogVec)    
dogdf.insert(loc=0,column ="label",value=0)


Processing file : dog-and-cats-images/train/dogs/dog_479.jpg
Processing file : dog-and-cats-images/train/dogs/dog_287.jpg
Processing file : dog-and-cats-images/train/dogs/dog_231.jpg
Processing file : dog-and-cats-images/train/dogs/dog_509.jpg
Processing file : dog-and-cats-images/train/dogs/dog_277.jpg


/tmp/ipykernel_11869/2184810192.py:5: DeprecationWarning: Starting with ImageIO v3 the behavior of this function will switch to that of iio.v3.imread. To keep the current behavior (and make this warning disappear) use `import imageio.v2 as imageio` or call `imageio.v2.imread` directly.
  img = imageio.imread(f"{dogdir}/{img}")


In [40]:
print(dogdf.head(5))

   label    0    1    2    3    4    5    6    7    8  ...  4319990  4319991   
0      0  239  237  216  239  237  216  239  237  216  ...      NaN      NaN  \
1      0  252  251  247  252  251  247  252  251  247  ...      NaN      NaN   
2      0   37   53    8   37   53    8   37   53    8  ...      NaN      NaN   
3      0  238  241  246  238  241  246  238  241  246  ...      NaN      NaN   
4      0    4   20    0    0   23    0   20   53    0  ...    211.0    158.0   

   4319992  4319993  4319994  4319995  4319996  4319997  4319998  4319999  
0      NaN      NaN      NaN      NaN      NaN      NaN      NaN      NaN  
1      NaN      NaN      NaN      NaN      NaN      NaN      NaN      NaN  
2      NaN      NaN      NaN      NaN      NaN      NaN      NaN      NaN  
3      NaN      NaN      NaN      NaN      NaN      NaN      NaN      NaN  
4    188.0    212.0    158.0    188.0    212.0    159.0    189.0    213.0  

[5 rows x 4320001 columns]


In [41]:
data = pd.concat([catdf,dogdf])      
data = data.sample(frac=1)
## now we have dataset with label for each of our images.

In [42]:
data.head()

label    0    1    2    3    4    5    6    7    8  ...  4319990  4319991   
4      0    4   20    0    0   23    0   20   53    0  ...    211.0    158.0  \
2      0   37   53    8   37   53    8   37   53    8  ...      NaN      NaN   
3      1    0    0    0    0    0    0    0    0    0  ...      NaN      NaN   
3      0  238  241  246  238  241  246  238  241  246  ...      NaN      NaN   
1      1  222  216  218  222  216  218  222  216  218  ...      NaN      NaN   

   4319992  4319993  4319994  4319995  4319996  4319997  4319998  4319999  
4    188.0    212.0    158.0    188.0    212.0    159.0    189.0    213.0  
2      NaN      NaN      NaN      NaN      NaN      NaN      NaN      NaN  
3      NaN      NaN      NaN      NaN      NaN      NaN      NaN      NaN  
3      NaN      NaN      NaN      NaN      NaN      NaN      NaN      NaN  
1      NaN      NaN      NaN      NaN      NaN      NaN      NaN      NaN  

[5 rows x 4320001 columns]

In [44]:
data.info

<bound method DataFrame.info of    label    0    1    2    3    4    5    6    7    8  ...  4319990  4319991   
4      0    4   20    0    0   23    0   20   53    0  ...    211.0    158.0  \
2      0   37   53    8   37   53    8   37   53    8  ...      NaN      NaN   
3      1    0    0    0    0    0    0    0    0    0  ...      NaN      NaN   
3      0  238  241  246  238  241  246  238  241  246  ...      NaN      NaN   
1      1  222  216  218  222  216  218  222  216  218  ...      NaN      NaN   
4      1  152  171  143  152  171  143  152  171  143  ...      NaN      NaN   
0      1   93   87   65   89   83   61   81   75   53  ...      NaN      NaN   
2      1   36   67   36   36   67   36   36   67   36  ...      NaN      NaN   
1      0  252  251  247  252  251  247  252  251  247  ...      NaN      NaN   
0      0  239  237  216  239  237  216  239  237  216  ...      NaN      NaN   

   4319992  4319993  4319994  4319995  4319996  4319997  4319998  4319999  
4    188.0 

In [52]:
from sklearn.model_selection import train_test_split
from sklearn.neighbors import KNeighborsClassifier

## X=data.iloc[:,1] ## all rows, from column1 to last Column
## Y=data['label']

X=data.iloc[:,1].values ## all rows, from column1 to last Column
Y=data['label'].values


In [53]:
X

array([  4,  37,   0, 238, 222, 152,  93,  36, 252, 239], dtype=uint8)

In [54]:
Y

array([0, 0, 1, 0, 1, 1, 1, 1, 0, 0])

In [55]:

X=X.reshape(-1,1)


In [56]:
X

array([[  4],
       [ 37],
       [  0],
       [238],
       [222],
       [152],
       [ 93],
       [ 36],
       [252],
       [239]], dtype=uint8)

In [57]:
Y

array([0, 0, 1, 0, 1, 1, 1, 1, 0, 0])

In [58]:
X_train, X_test, y_train, y_test = train_test_split(X, Y, test_size = 0.25)

model = KNeighborsClassifier(n_neighbors=1)
fit = model.fit(X_train, y_train)

In [59]:
## Just set the n_neighbors values
## knn = KNeighborsClassifier(n_neighbors=1)

In [60]:
## y_pred = knn.predict(X_test)

y_pred = model.predict(X_test)

from sklearn.metrics import r2_score

r2 = r2_score(y_test, y_pred)

print("R2 score:", r2)


R2 score: 0.0


In [61]:
from sklearn.metrics import classification_report
    
## print(classification_report(y_test, regr.predict(X_test))

print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           0       0.00      0.00      0.00         0
           1       1.00      0.33      0.50         3

    accuracy                           0.33         3
   macro avg       0.50      0.17      0.25         3
weighted avg       1.00      0.33      0.50         3



/home/giri/python/notebookenv/lib/python3.8/site-packages/sklearn/metrics/_classification.py:1469: UndefinedMetricWarning: Recall and F-score are ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/home/giri/python/notebookenv/lib/python3.8/site-packages/sklearn/metrics/_classification.py:1469: UndefinedMetricWarning: Recall and F-score are ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/home/giri/python/notebookenv/lib/python3.8/site-packages/sklearn/metrics/_classification.py:1469: UndefinedMetricWarning: Recall and F-score are ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


In [62]:
## X = [[0], [1], [2], [3]]
## y = [0, 0, 1, 1]
from sklearn.neighbors import KNeighborsClassifier
neigh = KNeighborsClassifier(n_neighbors=3)
## neigh.fit(X, y) 
fit = neigh.fit(X_train, y_train)

print(neigh.predict([[1.1]]))

print(neigh.predict_proba([[0.9]]))

[0]
[[0.66666667 0.33333333]]
